# 项目信息 / Project information
site_name: Hello-Astronomy  # 网站名称
site_description: 探索有趣的旅程  # 网站描述
site_author: Xia0-0  # 作者署名

# 仓库信息 / Repository
repo_url: https://github.com/Xia0-0/Hello-Astronomy
repo_name: GitHub

# 自定义配置部分 / Configuration
theme:
  name: material
  custom_dir: docs/overrides  # 自定义主题目录，用于覆盖默认样式
  language: zh
  favicon: assets/images/favicon.ico  # 网站图标
  logo: assets/images/logo.png  # 网站 Logo

  palette:  # 调色板配置
    - scheme: slate  # 深色模式
      primary: black  # 主色调
      accent: teal  # 强调色
      toggle:  # 深浅模式切换按钮
        icon: material/weather-night  # 夜空主题图标
        name: 长夜漫漫  # 提示文字
    - scheme: light
      primary: white
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: 旭日东升

extra_javascript:
  - javascripts/mathjax.js # 自定义js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true 

extra:
  site_url: https://hello-astronomy.com  # 网站 URL
  social:  # 社交链接配置
    - icon: fontawesome/brands/twitter  # Twitter 图标
      link: https://x.com/Xia0_0_G  # Twitter 链接
    - icon: xiaohongshu # 自定义小红书图标
      link: https://xiaohongshu.com/user/profile/65ccd77a0000000005033d02
    - icon: fontawesome/brands/github
      link: https://github.com/Xia0-0/Hello-Astronomy


nav:
  - 首页: index.md

  - 基础入门:
      - 天文学概论: basic/astronomy_overview.md
      - 时间与历法: basic/time_and_calendar.md
      - 天球与坐标: basic/sky_and_coordinates.md
      - 行星与恒星: basic/planets_and_stars.md
      - 星系与星系团: basic/galaxies_and_galaxy_clusters.md
      - 宇宙大尺度下的视角: basic/cosmology.md

  - 天体物理: 
      - 轨道力学: physics/gravitation.md
      - 辐射理论: physics/radiation.md
      - 恒星物理: physics/stellar_physics.md
      - 星系学: physics/spectroscopy.md
      - 宇宙学: physics/galaxy_physics.md
    
  - 实用技术:
      - 天体观测: technique/astronomical_observations.md
      - 天文摄影: technique/astronomy_photography.md
      - 计算机: technique/computer.md
  
  - 其他:
      - 资源: other/resources.md
