name: Build and Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 允许 bot 对仓库内容进行写操作

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install mkdocs mkdocs-material

    - name: Build MkDocs site
      run: mkdocs build

    - name: Commit and Push to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Actions 提供的默认 Token
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git fetch origin gh-pages || git checkout --orphan gh-pages
        git rm -rf .
        rm -rf site
        cp -r site/* .
        
        git add .
        git commit -m "Update site [skip ci]" || echo "No changes to commit"
        git push origin gh-pages 
