name: Build and Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 允许 bot 对仓库内容进行写操作

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build

      - name: Setup gh-pages branch
        run: |
          git fetch origin gh-pages || echo "No gh-pages branch, skipping fetch"

      - name: Copy built site to docs
        run: mv site/* docs/  # 直接将内容移动，而不是删除 docs 目录

      - name: Commit and Push to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Actions 提供的默认 Token
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*
          git diff --quiet && exit 0  
          git commit -m "Update site [skip ci]"
          git push origin gh-pages
